// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  define([], function() {
    var read, readSongAnalyses, readSongs, set, setSongAnalyses, setSongs;
    read = function() {
      return JSON.parse(window.sessionStorage.getItem('gameState'));
    };
    set = function(gs) {
      return window.sessionStorage.setItem('gameState', JSON.stringify(gs));
    };
    readSongs = function() {
      return JSON.parse(window.sessionStorage.getItem('songState'));
    };
    setSongs = function(ss) {
      return window.sessionStorage.setItem('songState', JSON.stringify(ss));
    };
    readSongAnalyses = function() {
      return JSON.parse(window.sessionStorage.getItem('songAnalysis'));
    };
    setSongAnalyses = function(sa) {
      return window.sessionStorage.setItem('songAnalysis', JSON.stringify(sa));
    };
    return {
      read: read,
      set: set,
      songs: {
        read: readSongs,
        set: setSongs
      },
      song_analyses: {
        read: readSongAnalyses,
        set: setSongAnalyses
      }
    };
  });

}).call(this);

//# sourceMappingURL=state.js.map
